name: Build BusyBox for Android

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git make unzip

    - name: Download Android Command-line Tools
      run: |
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-13114758_latest.zip
        unzip -q commandlinetools-linux-*.zip -d cmdline-tools
        mv cmdline-tools/cmdline-tools cmdline-tools/latest  # 修复目录结构
        rm commandlinetools-linux-*.zip

    - name: Setup Android SDK
      run: |
        echo "ANDROID_HOME=$PWD/android-sdk" >> $GITHUB_ENV
        mkdir -p $ANDROID_HOME

    - name: Accept Android Licenses
      run: |
        yes | cmdline-tools/latest/bin/sdkmanager \
          --sdk_root=$ANDROID_HOME \
          --licenses

    - name: Install Android NDK
      run: |
        cmdline-tools/latest/bin/sdkmanager \
          --sdk_root=$ANDROID_HOME \
          --install "ndk;28.0.13004108"

    - name: Configure NDK Path
      run: |
        echo "NDK_HOME=$ANDROID_HOME/ndk/28.0.13004108" >> $GITHUB_ENV
        echo "$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH

    - name: Checkout BusyBox
      run: |
        git clone https://git.busybox.net/busybox/
        cd busybox
        git checkout master

    - name: Configure BusyBox
      run: |
        cd busybox
        make defconfig
        # 修改配置以支持 Android 交叉编译
        sed -i 's/CONFIG_CROSS_COMPILER_PREFIX=".*"/CONFIG_CROSS_COMPILER_PREFIX="aarch64-linux-android35-"/' .config
        sed -i 's/CONFIG_EXTRA_CFLAGS=".*"/CONFIG_EXTRA_CFLAGS="-static -fPIE -pie"/' .config
        sed -i 's/CONFIG_FEATURE_USE_INITTAB=y/# CONFIG_FEATURE_USE_INITTAB is not set/' .config

    - name: Build BusyBox
      run: |
        cd busybox
        make CC=aarch64-linux-android35-clang \
             CROSS_COMPILE=aarch64-linux-android35- \
             ARCH=arm64 \
             SYSROOT=$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot

    - name: Verify binary
      run: |
        file busybox/busybox
        readelf -h busybox/busybox | grep -q 'AArch64' || (echo "Wrong architecture"; exit 1)
        readelf -h busybox/busybox | grep -q 'UNIX - Android' || (echo "Not Android binary"; exit 1)

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: busybox-android-arm64
        path: busybox/busybox
