name: Build BusyBox for Android

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git make unzip python3

    - name: Configure Git
      run: |
        git config --global http.postBuffer 1048576000
        git config --global core.compression 9

    - name: Download Android Command-line Tools
      run: |
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-13114758_latest.zip
        unzip -q commandlinetools-linux-*.zip -d cmdline-tools
        mv cmdline-tools/cmdline-tools cmdline-tools/latest
        rm commandlinetools-linux-*.zip

    - name: Setup Android SDK
      run: |
        echo "ANDROID_SDK_ROOT=$PWD/android-sdk" >> $GITHUB_ENV
        mkdir -p $ANDROID_SDK_ROOT

    - name: Accept Android Licenses
      run: |
        yes | cmdline-tools/latest/bin/sdkmanager \
          --sdk_root=$ANDROID_SDK_ROOT \
          --licenses

    - name: Install Android NDK
      run: |
        cmdline-tools/latest/bin/sdkmanager \
          --sdk_root=$ANDROID_SDK_ROOT \
          --install "ndk;28.0.13004108"

    - name: Configure NDK Path
      run: |
        NDK_PATH="$ANDROID_SDK_ROOT/ndk/28.0.13004108"
        echo "NDK_ROOT=$NDK_PATH" >> $GITHUB_ENV
        echo "CLANG_BIN=$NDK_PATH/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_ENV
        echo "CLANG_PATH=$NDK_PATH/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android35-clang" >> $GITHUB_ENV
        echo "$CLANG_BIN" >> $GITHUB_PATH

    - name: Verify toolchain
      run: |
        echo "Android SDK路径: $ANDROID_SDK_ROOT"
        echo "NDK绝对路径: $(realpath $NDK_ROOT)"
        echo "编译器路径: $CLANG_PATH"
        ls -l "$CLANG_PATH"
        file "$CLANG_PATH"

    - name: Clone BusyBox (with retry)
      run: |
        for i in {1..3}; do
          git clone https://github.com/mirror/busybox.git && break || sleep 15
          [[ $i -eq 3 ]] && exit 1
        done

    - name: Configure BusyBox
      run: |
        cd busybox
        make defconfig
        # 修复编译器路径配置
        sed -i "s|CONFIG_CROSS_COMPILER_PREFIX=.*|CONFIG_CROSS_COMPILER_PREFIX=\"aarch64-linux-android35-\"|" .config
        sed -i "s|CONFIG_EXTRA_CFLAGS=.*|CONFIG_EXTRA_CFLAGS=\"-static -fPIE -pie --target=aarch64-linux-android35 --sysroot=$NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/sysroot\"|" .config
        sed -i "s|CONFIG_FEATURE_USE_INITTAB=y|# CONFIG_FEATURE_USE_INITTAB is not set|" .config
        echo "CONFIG_EXTRA_LDFLAGS=\"--sysroot=$NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/sysroot\"" >> .config

    - name: Build BusyBox
      run: |
        cd busybox
        echo "当前编译器路径: $(which aarch64-linux-android35-clang)"
        make CC="$CLANG_PATH" \
             CROSS_COMPILE=aarch64-linux-android35- \
             ARCH=arm64 \
             CFLAGS="--sysroot=$NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/sysroot" \
             LDFLAGS="--sysroot=$NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/sysroot"

    - name: Verify binary
      run: |
        file busybox/busybox
        readelf -h busybox/busybox | grep -q 'AArch64' || (echo "架构错误"; exit 1)
        readelf -h busybox/busybox | grep -q 'UNIX - Android' || (echo "非Android可执行文件"; exit 1)

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: busybox-android-arm64
        path: busybox/busybox
