name: Build BusyBox for Android

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git make unzip

    - name: Download Android Command-line Tools
      run: |
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-13114758_latest.zip
        unzip -q commandlinetools-linux-*.zip -d cmdline-tools
        mv cmdline-tools/cmdline-tools cmdline-tools/latest
        rm commandlinetools-linux-*.zip

    - name: Setup Android SDK
      run: |
        echo "ANDROID_HOME=$PWD/android-sdk" >> $GITHUB_ENV
        mkdir -p $ANDROID_HOME

    - name: Accept Android Licenses
      run: |
        yes | cmdline-tools/latest/bin/sdkmanager \
          --sdk_root=$ANDROID_HOME \
          --licenses

    - name: Install Android NDK
      run: |
        cmdline-tools/latest/bin/sdkmanager \
          --sdk_root=$ANDROID_HOME \
          --install "ndk;28.0.13004108"

    - name: Configure NDK Path
      run: |
        echo "NDK_HOME=$ANDROID_HOME/ndk/28.0.13004108" >> $GITHUB_ENV
        echo "$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH
        echo "CLANG_PATH=$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android35-clang" >> $GITHUB_ENV

    - name: Check toolchain availability
      run: |
        ls -l $NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin
        which aarch64-linux-android35-clang

    - name: Checkout BusyBox
      run: |
        git clone https://git.busybox.net/busybox/
        cd busybox
        git checkout master

    - name: Configure BusyBox
      run: |
        cd busybox
        make defconfig
        # 修复编译器路径配置
        sed -i 's|CONFIG_CROSS_COMPILER_PREFIX=".*"|CONFIG_CROSS_COMPILER_PREFIX="aarch64-linux-android-"|' .config
        sed -i 's|CONFIG_EXTRA_CFLAGS=".*"|CONFIG_EXTRA_CFLAGS="-static -fPIE -pie --target=aarch64-linux-android35 --sysroot=$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot"|' .config
        sed -i 's|CONFIG_FEATURE_USE_INITTAB=y|# CONFIG_FEATURE_USE_INITTAB is not set|' .config
        echo "CONFIG_EXTRA_LDFLAGS=\"--target=aarch64-linux-android35 --sysroot=$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot\"" >> .config

    - name: Build BusyBox
      run: |
        cd busybox
        export PATH=$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
        make CC="$CLANG_PATH" \
             CROSS_COMPILE=aarch64-linux-android- \
             ARCH=arm64 \
             CFLAGS="--target=aarch64-linux-android35" \
             LDFLAGS="--target=aarch64-linux-android35"

    - name: Verify binary
      run: |
        file busybox/busybox
        readelf -h busybox/busybox | grep -q 'AArch64' || (echo "Wrong architecture"; exit 1)
        readelf -h busybox/busybox | grep -q 'UNIX - Android' || (echo "Not Android binary"; exit 1)

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: busybox-android-arm64
        path: busybox/busybox
