name: 极简Android编译器

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 安装NDK
      uses: android-actions/setup-android-ndk@v2
      with:
        ndk-version: 25c

    - name: 查找C文件
      id: find-sources
      run: |
        # 搜索当前目录及子目录下的所有.c文件
        c_files=$(find . -name '*.c' -not -path '*/.*')
        if [ -z "$c_files" ]; then
          echo "::error::未找到任何C源文件"
          exit 1
        fi
        # 获取第一个文件名作为可执行文件名
        exec_name=$(basename $(echo "$c_files" | head -n1) .c)
        echo "exec_name=$exec_name" >> $GITHUB_OUTPUT
        echo "找到源文件：$c_files"

    - name: 编译ARM64程序
      run: |
        mkdir -p bin
        compiler="$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang"
        sysroot="$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot"
        
        $compiler -pie --sysroot="$sysroot" \
          -o "bin/${{ steps.find-sources.outputs.exec_name }}" \
          $(find . -name '*.c')
        
        echo "编译完成！生成文件："
        ls -lh bin/
