name: Android ARM64 Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup path
      run: |
        grep -E '^(nbbm|aapi|cbbm)=' config.env >> $GITHUB_ENV

    # 修复点1：缓存路径使用明确格式
    - name: Cache Android SDK
      uses: actions/cache@v3
      id: sdk-cache
      with:
        path: |
          ~/android-sdk/cmdline-tools
          ~/android-sdk/licenses
        key: android-sdk-${{ env.cbbm }}

    # 修复点2：添加SDK_ROOT环境变量
    - name: Setup Android SDK
      if: steps.sdk-cache.outputs.cache-hit != 'true'
      run: |
        mkdir -p ~/android-sdk
        wget https://dl.google.com/android/repository/${{ env.cbbm }} -O cmdline-tools.zip
        unzip cmdline-tools.zip -d ~/android-sdk/cmdline-tools
        mv ~/android-sdk/cmdline-tools/cmdline-tools ~/android-sdk/cmdline-tools/latest
        yes | ~/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
        echo "ANDROID_HOME=~/android-sdk" >> $GITHUB_ENV

    - name: Set Android Path
      run: |
        echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH

    - name: Cache NDK
      uses: actions/cache@v3
      id: ndk-cache
      with:
        path: $ANDROID_HOME/ndk/${{ env.nbbm }}
        key: android-ndk-${{ env.nbbm }}

    # 修复点3：优化NDK安装条件判断
    - name: Install NDK
      if: steps.ndk-cache.outputs.cache-hit != 'true'
      run: |
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
          "ndk;${{ env.nbbm }}" \
          --sdk_root=$ANDROID_HOME

    - name: Setup NDK
      run: |
        echo "NDK_HOME=$ANDROID_HOME/ndk/${{ env.nbbm }}" >> $GITHUB_ENV
        echo "$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH

    # 以下保持原样...
    - name: Verify NDK Installation
      run: |
        echo "NDK路径: $NDK_HOME"
        ls -l $NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/clang

    - name: Find C file
      id: find-c-file
      run: |
        c_files=( *.c )
        if [ ${#c_files[@]} -ne 1 ]; then
          echo "::error::必须且只能存在一个.c文件 (当前找到 ${#c_files[@]} 个)"
          exit 1
        fi
        echo "C_FILE=${c_files[0]}" >> $GITHUB_OUTPUT
        echo "OUTPUT_NAME=${c_files[0]%.*}" >> $GITHUB_OUTPUT

    - name: Build executable
      run: |
        $NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/clang \
          --target=aarch64-linux-android${{ env.aapi }} \
          --sysroot=$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot \
          -fPIE -pie \
          -o "${{ steps.find-c-file.outputs.OUTPUT_NAME }}" \
          "${{ steps.find-c-file.outputs.C_FILE }}"

    - name: Verify binary
      run: |
        file "${{ steps.find-c-file.outputs.OUTPUT_NAME }}"
        readelf -d "${{ steps.find-c-file.outputs.OUTPUT_NAME }}"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-binary
        path: "${{ steps.find-c-file.outputs.OUTPUT_NAME }}"
