name: Advanced C/C++ Builder

on:
  push:
    branches: [ main ]
    tags: ['v*']
  workflow_dispatch:
    inputs:
      build_subdir:
        description: '是否编译子目录？ (yes/no)'
        required: true
        type: choice
        options:
          - no
          - yes
        default: 'no'
      subdir_path:
        description: '请输入要编译的子目录路径（留空则自动检测）'
        required: false
        default: ''
      target_arch:
        description: '选择目标架构'
        required: true
        type: choice
        options:
          - arm32
          - arm64
        default: 'arm64'
      compile_flags:
        description: '自定义编译参数（默认：-pie）'
        required: false
        default: '-pie'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # 自动设置默认值
      BUILD_SUBDIR: ${{ github.event.inputs.build_subdir || 'no' }}
      SUBDIR_PATH: ${{ github.event.inputs.subdir_path || '' }}
      TARGET_ARCH: ${{ github.event.inputs.target_arch || 'arm64' }}
      COMPILE_FLAGS: ${{ github.event.inputs.compile_flags || '-pie' }}
    outputs:
      exec_name: ${{ steps.detect.outputs.exec_name }}
      release_tag: ${{ steps.get_tag.outputs.tag }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 获取完整的提交历史用于标签检测

    - name: Get version tag
      id: get_tag
      run: |
        if [[ "$GITHUB_REF" == refs/tags/* ]]; then
          tag="${GITHUB_REF#refs/tags/}"
        else
          # 获取最新的标签（按时间排序）
          latest_tag=$(git tag --sort=-creatordate | head -n 1)
          if [ -z "$latest_tag" ]; then
            latest_tag="nightly-$(date +%Y%m%d)"
            echo "生成临时标签: $latest_tag"
          fi
          tag="$latest_tag"
        fi
        echo "tag=$tag" >> $GITHUB_OUTPUT

    - name: Cache toolchain
      uses: actions/cache@v4
      id: cache-toolchain
      with:
        path: |
          ~/apt-cache
          /usr/bin/*-linux-gnu*
        key: ${{ runner.os }}-$TARGET_ARCH-$(date -u +'%Y%m%d')
        restore-keys: |
          ${{ runner.os }}-$TARGET_ARCH-

    - name: Setup toolchain
      run: |
        sudo mkdir -p ~/apt-cache/archives
        sudo ln -sf ~/apt-cache/archives /var/cache/apt/archives
        
        # 检查工具链是否存在
        case "$TARGET_ARCH" in
          arm32)
            if ! dpkg -l | grep -q 'gcc-arm-linux-gnueabi'; then
              sudo apt-get update
              sudo apt-get install -y gcc-arm-linux-gnueabi g++-arm-linux-gnueabi
            fi
            ;;
          arm64)
            if ! dpkg -l | grep -q 'gcc-aarch64-linux-gnu'; then
              sudo apt-get update
              sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
            fi
            ;;
        esac

    - name: Detect source files
      id: detect
      run: |
        search_path="."
        if [[ "${{ github.event.inputs.build_subdir }}" == "yes" ]]; then
          search_path="${ { github.event.inputs.subdir_path }:-*}"
          search_path="${search_path%/}/"
        fi

        # Find source files
        c_files=$(find "$search_path" -name '*.c' -not -path '*/.*')
        cpp_files=$(find "$search_path" -name '*.cpp' -o -name '*.cc' -not -path '*/.*')
        all_files=$(echo -e "$c_files\n$cpp_files" | grep -v '^$')
        
        if [ -z "$all_files" ]; then
          echo "::error::未找到任何源文件"
          exit 1
        fi

        # Determine compiler type
        if [ -n "$cpp_files" ]; then
          echo "compiler_type=g++" >> $GITHUB_OUTPUT
        else
          echo "compiler_type=gcc" >> $GITHUB_OUTPUT
        fi

        # Get main filename
        first_file=$(echo "$all_files" | head -n1 | xargs basename -s .c | sed 's/\.cpp$//;s/\.cc$//')
        echo "exec_name=$first_file" >> $GITHUB_OUTPUT
        echo "source_files=$all_files" >> $GITHUB_OUTPUT

    - name: Compile
      run: |
        # Create output directory
        mkdir -p bin

        # Set compiler
        case "$TARGET_ARCH" in
          arm32)
            [ "${{ steps.detect.outputs.compiler_type }}" = "g++" ] && \
              compiler=arm-linux-gnueabi-g++ || \
              compiler=arm-linux-gnueabi-gcc
            suffix="-arm32"
            ;;
          arm64)
            [ "${{ steps.detect.outputs.compiler_type }}" = "g++" ] && \
              compiler=aarch64-linux-gnu-g++ || \
              compiler=aarch64-linux-gnu-gcc
            suffix="-arm64"
            ;;
          *)
            [ "${{ steps.detect.outputs.compiler_type }}" = "g++" ] && \
              compiler=aarch64-linux-gnu-g++ || \
              compiler=aarch64-linux-gnu-gcc
            suffix="-arm64"
            ;;
        esac

        $compiler ${{ github.event.inputs.compile_flags }} -static \
          -o "bin/${{ steps.detect.outputs.exec_name }}${suffix}" \
          ${{ steps.detect.outputs.source_files }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.detect.outputs.exec_name }}_$TARGET_ARCH
        path: bin/${{ steps.detect.outputs.exec_name }}*          
        # 添加保留目录结构参数
        retention-days: 1
        if-no-files-found: error
        
  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ needs.build.outputs.exec_name }}_$TARGET_ARCH
        path: release_files

    - name: Create Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ needs.build.outputs.release_tag }}
        name: "${{ needs.build.outputs.release_tag }} ($TARGET_ARCH)"
        files: |
          release_files/*
        draft: false
        prerelease: false
        generate_release_notes: true
